title: Sanaa Igbokwe 
logo: "images/2023 Headshot.jpg"
description: >
  Syracuse University Alum, graduated Magna cum Laude May 2023 from the School of Information Studies. Passionate about data science and innovation for assisting marginalized communities and sustainability.
  <br><br>
  
  <a href="https://www.linkedin.com/in/sanaaigbokwe/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-L1G8GS6SS6 
