title: Sanaa Igbokwe 
logo: "images/2023 Headshot.jpg"
description: >
  Sanaa Igbokwe is a data analyst who illuminates insights and drives decision-making by unraveling complex datasets with precision and creativity. They know that data analysis is not just about numbers; it's about understanding human behavior and societal trends.
  <br><br>
  
  <a href="https://www.linkedin.com/in/sanaaigbokwe/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-L1G8GS6SS6 
